<<<<<<< HEAD
USE [DA_WINFORM]
GO
/****** Object:  Table [dbo].[Contacts]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
	[Phone] [nvarchar](20) NULL,
	[Address] [nvarchar](255) NULL,
	[Company] [nvarchar](100) NULL,
	[GuestCount] [int] NULL,
	[Subject] [nvarchar](255) NULL,
	[Content] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHAMCONGNV]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHAMCONGNV](
	[MANV] [varchar](10) NOT NULL,
	[NGAYLAM] [datetime] NOT NULL,
	[HSL] [float] NULL,
	[TIENLUONG] [decimal](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[NGAYLAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIEMDI]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIEMDI](
	[MADDI] [varchar](10) NOT NULL,
	[TENDDI] [nvarchar](200) NOT NULL,
	[MALTOUR] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MADDI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIEMDULICH]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIEMDULICH](
	[MADDEN] [varchar](10) NOT NULL,
	[TENDDEN] [nvarchar](200) NOT NULL,
	[MALTOUR] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MADDEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[SOHD] [varchar](10) NOT NULL,
	[MATOUR] [varchar](10) NOT NULL,
	[MANV] [varchar](10) NOT NULL,
	[MAKH] [varchar](10) NOT NULL,
	[NGAYLAPHOADON] [datetime] NOT NULL,
	[THANHTIENHOADON] [decimal](18, 0) NULL,
	[TRANGTHAI] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[SOHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [varchar](10) NOT NULL,
	[TENKH] [nvarchar](200) NOT NULL,
	[SDT] [varchar](12) NOT NULL,
	[EMAIL] [nvarchar](50) NOT NULL,
	[DIACHI] [nvarchar](255) NOT NULL,
	[UUDAI] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHSAN]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHSAN](
	[MAKS] [varchar](10) NOT NULL,
	[TENKS] [nvarchar](200) NOT NULL,
	[GIAKS] [decimal](18, 0) NOT NULL,
	[DIACHI] [nvarchar](255) NOT NULL,
	[MALKS] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICHSUCHITIET]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICHSUCHITIET](
	[MATV] [int] IDENTITY(1,1) NOT NULL,
	[SOHD] [varchar](10) NULL,
	[MALLT] [varchar](10) NULL,
	[TENTV] [nvarchar](255) NULL,
	[GIOITINH] [nvarchar](10) NULL,
	[NGAYSINH] [date] NULL,
	[THANHTIENKH] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[MATV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIKS]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIKS](
	[MALKS] [varchar](10) NOT NULL,
	[TENLKS] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALKS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAILUATUOI]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAILUATUOI](
	[MALLT] [varchar](10) NOT NULL,
	[TENLLT] [nvarchar](200) NOT NULL,
	[GIATIENLLT] [decimal](18, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALLT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAITOUR]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAITOUR](
	[MALTOUR] [varchar](10) NOT NULL,
	[TENLTOUR] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALTOUR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [varchar](10) NOT NULL,
	[TENNV] [nvarchar](200) NOT NULL,
	[NGSINH] [date] NOT NULL,
	[SDT] [decimal](18, 0) NOT NULL,
	[CMND_CCCD] [decimal](18, 0) NOT NULL,
	[NGVL] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHUONGTIEN]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHUONGTIEN](
	[MAPT] [varchar](10) NOT NULL,
	[TENPT] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAPT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAIKHOANKHACHHANG]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOANKHACHHANG](
	[UserName] [varchar](50) NOT NULL,
	[MAKH] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TOUR]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOUR](
	[MATOUR] [varchar](10) NOT NULL,
	[TENTOUR] [nvarchar](200) NOT NULL,
	[MOTA] [nvarchar](max) NOT NULL,
	[SOLUONGCONLAI] [int] NOT NULL,
	[NGAYDITOUR] [datetime] NOT NULL,
	[NGAYKETTHUC] [datetime] NOT NULL,
	[ANH1] [image] NULL,
	[ANH2] [image] NULL,
	[ANH3] [image] NULL,
	[ANH4] [image] NULL,
	[GIATOUR] [decimal](18, 0) NOT NULL,
	[MALTOUR] [varchar](10) NOT NULL,
	[MAPT] [varchar](10) NOT NULL,
	[MADDI] [varchar](10) NOT NULL,
	[MADDEN] [varchar](10) NOT NULL,
	[MALKS] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MATOUR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[IDUSER] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](20) NOT NULL,
	[Password] [varchar](20) NOT NULL,
	[QUYEN] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUSER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHAMCONGNV]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[CHAMCONGNV]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[DIEMDI]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[DIEMDI]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[DIEMDULICH]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[DIEMDULICH]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MATOUR])
REFERENCES [dbo].[TOUR] ([MATOUR])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MATOUR])
REFERENCES [dbo].[TOUR] ([MATOUR])
GO
ALTER TABLE [dbo].[KHACHSAN]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[KHACHSAN]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[TAIKHOANKHACHHANG]  WITH CHECK ADD FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDEN])
REFERENCES [dbo].[DIEMDULICH] ([MADDEN])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDEN])
REFERENCES [dbo].[DIEMDULICH] ([MADDEN])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDI])
REFERENCES [dbo].[DIEMDI] ([MADDI])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDI])
REFERENCES [dbo].[DIEMDI] ([MADDI])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MAPT])
REFERENCES [dbo].[PHUONGTIEN] ([MAPT])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MAPT])
REFERENCES [dbo].[PHUONGTIEN] ([MAPT])
GO
=======
USE [DA_WINFORM]
GO
/****** Object:  Table [dbo].[Contacts]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Email] [nvarchar](100) NULL,
	[Phone] [nvarchar](20) NULL,
	[Address] [nvarchar](255) NULL,
	[Company] [nvarchar](100) NULL,
	[GuestCount] [int] NULL,
	[Subject] [nvarchar](255) NULL,
	[Content] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHAMCONGNV]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHAMCONGNV](
	[MANV] [varchar](10) NOT NULL,
	[NGAYLAM] [datetime] NOT NULL,
	[HSL] [float] NULL,
	[TIENLUONG] [decimal](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC,
	[NGAYLAM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIEMDI]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIEMDI](
	[MADDI] [varchar](10) NOT NULL,
	[TENDDI] [nvarchar](200) NOT NULL,
	[MALTOUR] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MADDI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIEMDULICH]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIEMDULICH](
	[MADDEN] [varchar](10) NOT NULL,
	[TENDDEN] [nvarchar](200) NOT NULL,
	[MALTOUR] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MADDEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HOADON]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HOADON](
	[SOHD] [varchar](10) NOT NULL,
	[MATOUR] [varchar](10) NOT NULL,
	[MANV] [varchar](10) NOT NULL,
	[MAKH] [varchar](10) NOT NULL,
	[NGAYLAPHOADON] [datetime] NOT NULL,
	[THANHTIENHOADON] [decimal](18, 0) NULL,
	[TRANGTHAI] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[SOHD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHHANG]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHHANG](
	[MAKH] [varchar](10) NOT NULL,
	[TENKH] [nvarchar](200) NOT NULL,
	[SDT] [varchar](12) NOT NULL,
	[EMAIL] [nvarchar](50) NOT NULL,
	[DIACHI] [nvarchar](255) NOT NULL,
	[UUDAI] [nvarchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACHSAN]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACHSAN](
	[MAKS] [varchar](10) NOT NULL,
	[TENKS] [nvarchar](200) NOT NULL,
	[GIAKS] [decimal](18, 0) NOT NULL,
	[DIACHI] [nvarchar](255) NOT NULL,
	[MALKS] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAKS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LICHSUCHITIET]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LICHSUCHITIET](
	[MATV] [int] IDENTITY(1,1) NOT NULL,
	[SOHD] [varchar](10) NULL,
	[MALLT] [varchar](10) NULL,
	[TENTV] [nvarchar](255) NULL,
	[GIOITINH] [nvarchar](10) NULL,
	[NGAYSINH] [date] NULL,
	[THANHTIENKH] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[MATV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAIKS]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAIKS](
	[MALKS] [varchar](10) NOT NULL,
	[TENLKS] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALKS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAILUATUOI]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAILUATUOI](
	[MALLT] [varchar](10) NOT NULL,
	[TENLLT] [nvarchar](200) NOT NULL,
	[GIATIENLLT] [decimal](18, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALLT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAITOUR]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAITOUR](
	[MALTOUR] [varchar](10) NOT NULL,
	[TENLTOUR] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MALTOUR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANV] [varchar](10) NOT NULL,
	[TENNV] [nvarchar](200) NOT NULL,
	[NGSINH] [date] NOT NULL,
	[SDT] [decimal](18, 0) NOT NULL,
	[CMND_CCCD] [decimal](18, 0) NOT NULL,
	[NGVL] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MANV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHUONGTIEN]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHUONGTIEN](
	[MAPT] [varchar](10) NOT NULL,
	[TENPT] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MAPT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TAIKHOANKHACHHANG]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TAIKHOANKHACHHANG](
	[UserName] [varchar](50) NOT NULL,
	[MAKH] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MAKH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TOUR]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TOUR](
	[MATOUR] [varchar](10) NOT NULL,
	[TENTOUR] [nvarchar](200) NOT NULL,
	[MOTA] [nvarchar](max) NOT NULL,
	[SOLUONGCONLAI] [int] NOT NULL,
	[NGAYDITOUR] [datetime] NOT NULL,
	[NGAYKETTHUC] [datetime] NOT NULL,
	[ANH1] [image] NULL,
	[ANH2] [image] NULL,
	[ANH3] [image] NULL,
	[ANH4] [image] NULL,
	[GIATOUR] [decimal](18, 0) NOT NULL,
	[MALTOUR] [varchar](10) NOT NULL,
	[MAPT] [varchar](10) NOT NULL,
	[MADDI] [varchar](10) NOT NULL,
	[MADDEN] [varchar](10) NOT NULL,
	[MALKS] [varchar](10) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[MATOUR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USER]    Script Date: 09/04/2025 8:31:19 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USER](
	[IDUSER] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [varchar](20) NOT NULL,
	[Password] [varchar](20) NOT NULL,
	[QUYEN] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDUSER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHAMCONGNV]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[CHAMCONGNV]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[DIEMDI]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[DIEMDI]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[DIEMDULICH]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[DIEMDULICH]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MANV])
REFERENCES [dbo].[NHANVIEN] ([MANV])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MATOUR])
REFERENCES [dbo].[TOUR] ([MATOUR])
GO
ALTER TABLE [dbo].[HOADON]  WITH CHECK ADD FOREIGN KEY([MATOUR])
REFERENCES [dbo].[TOUR] ([MATOUR])
GO
ALTER TABLE [dbo].[KHACHSAN]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[KHACHSAN]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[TAIKHOANKHACHHANG]  WITH CHECK ADD FOREIGN KEY([MAKH])
REFERENCES [dbo].[KHACHHANG] ([MAKH])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDEN])
REFERENCES [dbo].[DIEMDULICH] ([MADDEN])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDEN])
REFERENCES [dbo].[DIEMDULICH] ([MADDEN])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDI])
REFERENCES [dbo].[DIEMDI] ([MADDI])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MADDI])
REFERENCES [dbo].[DIEMDI] ([MADDI])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALKS])
REFERENCES [dbo].[LOAIKS] ([MALKS])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MALTOUR])
REFERENCES [dbo].[LOAITOUR] ([MALTOUR])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MAPT])
REFERENCES [dbo].[PHUONGTIEN] ([MAPT])
GO
ALTER TABLE [dbo].[TOUR]  WITH CHECK ADD FOREIGN KEY([MAPT])
REFERENCES [dbo].[PHUONGTIEN] ([MAPT])
GO
>>>>>>> 1e81ceb33691f747dda5778359e090edcf36b783
